# Generated by Django 4.2.7 on 2025-11-03 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.CharField(help_text="Sketchfab model ID'si (örn: 07882e7524534be984ae3e7faca25517)", max_length=50, unique=True, verbose_name='Sketchfab Model ID')),
                ('title', models.CharField(default='DESIGN SLIDER', max_length=200, verbose_name='Başlık')),
                ('topic', models.CharField(default='Model', max_length=200, verbose_name='Konu')),
                ('description', models.TextField(default='Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia, laborum cumque dignissimos quidem atque et eligendi aperiam voluptates beatae maxime.', verbose_name='Açıklama')),
                ('detail_title', models.CharField(default='Model', max_length=200, verbose_name='Detay Başlığı')),
                ('detail_description', models.TextField(default='Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolor, reiciendis suscipit nobis nulla animi, modi explicabo quod corrupti impedit illo, accusantium in eaque nam quia adipisci aut distinctio porro eligendi.', verbose_name='Detay Açıklaması')),
                ('order', models.PositiveIntegerField(default=0, help_text="Carousel'de görünecek sıra (0 en başta)", verbose_name='Sıralama')),
                ('is_active', models.BooleanField(default=True, help_text="Carousel'de gösterilsin mi?", verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Carousel Öğesi',
                'verbose_name_plural': 'Carousel Öğeleri',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
