# Generated by Django 4.2.7 on 2025-11-03 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_url',
            field=models.URLField(blank=True, help_text="Kategori kartında gösterilecek görsel URL'i", null=True, verbose_name='Kategori Görseli URL'),
        ),
    ]
