# Generated by Django 4.2.7 on 2025-11-03 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_category_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='Kategori kartında gösterilecek görsel', null=True, upload_to='categories/', verbose_name='Kategori Görseli'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image_url',
            field=models.URLField(blank=True, help_text='Eğer görsel dosyası yoksa URL kullanın', null=True, verbose_name='Kategori Görseli URL'),
        ),
    ]
