# Generated by Django 4.2.7 on 2025-11-04 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_category_image_alter_category_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, verbose_name='Müşteri Adı')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-posta')),
                ('customer_address', models.TextField(verbose_name='Adres')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Mesaj/Not')),
                ('status', models.CharField(choices=[('pending', 'Beklemede'), ('confirmed', 'Onaylandı'), ('cancelled', 'İptal Edildi')], default='pending', max_length=20, verbose_name='Durum')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='main.product', verbose_name='Ürün')),
            ],
            options={
                'verbose_name': 'Sipariş',
                'verbose_name_plural': 'Siparişler',
                'ordering': ['-created_at'],
            },
        ),
    ]
